### ISSUE TITLE
Window doesn't open automatically when ASCAM is started on macOS (12.4)

### ISSUE THREAD

**Issue by eckuru** [AGPlested/ASCAM#15]
When trying to start ASCAM on a macOS Monterey I had problems. I am using a conda environment set up following the instructions on the README. I tried both using pythonw and using the automatically created `ascam` command.

Description:
After running `ascam` the standard logging information is printed and a window named "python" starts (appears in the tray). No error messages are displayed and the code runs through. The window isn't responsive and doesn't open (only appaers in the tray).

Solution:
The problem is solved by adding `os.environ['QT_MAC_WANTS_LAYER'] = '1'` in ascam.py 🙂

**Comment by aplested** [comment]
This is true and that is a great fix. I was doing it manually!

****************
Andrew Plested
