### ISSUE TITLE
The units of the threshold (first act) are incorrect (has currently 12 digits before decimal point)

### ISSUE THREAD

**Issue by opfermann** [AGPlested/ASCAM#4]
![screenshot 2019-01-21 at 11 06 13](https://user-images.githubusercontent.com/26271459/51467381-b90fba80-1d6c-11e9-933b-2eb2f64bcb12.png)

**Comment by imLew** [comment]
Not 100% sure what you mean. But I don't need to be to see that this needed improvement.
Change in the latest commit to only show 5 digits.
Please have a look to see if it's correct now.
